# Copyright 2024 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Derived from molecule-plugins[podman]

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{%   for var, value in item.env.items() %}
{%     if value %}
ENV {{ var }} {{ value }}
{%     endif %}
{%   endfor %}
{% endif %}

RUN dnf makecache && dnf --assumeyes install \
    python3 \
    python3-devel \
    python3-dnf \
    sudo \
    bash \
    iproute \
  && dnf clean all

CMD ["/sbin/init"]
