# Copyright 2025 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Gather Python details
  ansible.builtin.setup:
    gather_subset:
      - python

- name: Set Python version
  ansible.builtin.set_fact:
    __python_version: "{{ prereq_python_supported | first | string }}"

- name: Install supported Python packages
  when: prereq_python_upgrade
  block:
    - name: Install supported version of Python3
      when:
        prereq_python_supported |
        first |
        ansible.builtin.split(".") |
        first == "3"
      block:
        - name: Install Python3 packages
          ansible.builtin.package:
            name: "{{ prereq_python_packages | default(__python3_packages) }}"
            state: present

        - name: Set installed Python as /usr/bin/python3 alternative with high priority
          when: prereq_python_alternatives
          community.general.alternatives:
            name: python3
            link: /usr/bin/python3
            path: "{{ '/usr/bin/python' + __python_version }}"
            priority: 100

    - name: Install supported version of Python2
      when:
        prereq_python_supported |
        first |
        ansible.builtin.split(".") |
        first == "2"
      block:
        - name: Install Python2 packages
          ansible.builtin.package:
            name: "{{ prereq_python_packages | default(__python2_packages) }}"
            state: present

    - name: Set installed Python as /usr/bin/python alternative with high priority
      when: prereq_python_alternatives
      community.general.alternatives:
        name: python
        link: /usr/bin/python
        path: "{{ '/usr/bin/python' + __python_version }}"
        priority: 100

- name: install pip
  ansible.builtin.package:
    name: "{{ prereq_python_pip_packages | default((prereq_python_supported | first | ansible.builtin.split('.') | first == '3') | ternary(__python3_pip_packages, __python2_pip_packages)) }}"
    state: present
