---
# Copyright 2026 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


keycloak__container_name: keycloak-server
keycloak__container_image: quay.io/keycloak/keycloak
keycloak__container_tag: 26.0.7

keycloak__container_http_port: 8180
keycloak__container_https_port: 8543

keycloak__admin_username: "admin"
keycloak__admin_password: "{{ undef(hint='Please define the Keycloak authentication password') }}"

keycloak__system_username: keycloak
keycloak__system_groupname: keycloak

keycloak__docker_exe: /usr/bin/docker

# Keycloak container configuration options
keycloak__metrics_enabled: true
keycloak__health_enabled: true
keycloak__container_log_level: INFO
keycloak__proxy_mode: edge
keycloak__http_enabled: true
keycloak__https_enabled: true

# NOTE: For TLS (replace with external certs)
keycloak__container_domain_name: "{{ undef(hint='Please provide the default domain for the Keycloak service') }}"
keycloak__container_ip_address: "{{ undef(hint='Please provide the IP address for the Keycloak service') }}"
