---
# Copyright 2025 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# - name: Configure host and DNS networking
#   ansible.builtin.import_role:
#     name: prereq_network_dns
#   vars:
#     network_ip_address: "{{ ipaclient_ip_address }}"
#     network_dns_domain: "{{ ipaclient_domain }}"
#     network_dns_forwarders: "{{ ipaclient_dns_servers }}"

# TODO Should be a full reboot, not a dbus and logind restart
# - name: Update DBUS configuration (RHEL)
#   when: ansible_os_family == 'RedHat'
#   ansible.builtin.copy:
#     src: freeipa_dbus_session.conf
#     dest: /etc/dbus-1/session.d/freeipa.conf
#   notify:
#     - Restart DBUS
#     # - Restart logind

- name: Load OS-specific variables
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version'] }}.yml"
    - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['distribution'] }}.yml"
    - "{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_version'] }}.yml"
    - "{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['os_family'] }}.yml"
    - "default.yml"

- name: Configure FreeIPA client with OS-specific Python
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version'] }}.yml"
    - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['distribution'] }}.yml"
    - "{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_version'] }}.yml"
    - "{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['os_family'] }}.yml"
    - "default.yml"
